<#
.SYNOPSIS
    Deploys the canonical, portable wiki COMPILE_PROTOCOL.md into a target repo.

.DESCRIPTION
    Copies the master COMPILE_PROTOCOL.md (living next to this script) into a target
    repository's wiki output directory. The destination directory is resolved in this order:
      1. -OutputDir parameter, if given
      2. the "output" field of the target repo's .wiki-compiler.json, if present
      3. "wiki" (default)

    The protocol itself is project-agnostic: it reads all project-specific values from the
    target's .wiki-compiler.json at runtime, so nothing in the copied file needs editing.

    With -InlineConfig, the script appends an auto-generated "Resolved configuration"
    appendix to the deployed copy, built from the target's .wiki-compiler.json. This
    specializes the copy for that project (concrete values inlined for the agent) while
    keeping the master generic. The appendix is regenerated fresh on every redeploy, so
    there is no manual drift — just redeploy with -Force -InlineConfig after editing config.

.PARAMETER TargetRepo
    Path to the destination repository root.

.PARAMETER OutputDir
    Override the output directory (relative to TargetRepo, or absolute). Skips config lookup.

.PARAMETER InlineConfig
    Append a project-specific "Resolved configuration" appendix generated from the target's
    .wiki-compiler.json. No-op (with a warning) if the target has no config.

.PARAMETER Force
    Overwrite an existing COMPILE_PROTOCOL.md at the destination. Required to redeploy.

.EXAMPLE
    .\deploy-protocol.ps1 -TargetRepo C:\Users\mrfin\Documents\some_project

.EXAMPLE
    .\deploy-protocol.ps1 -TargetRepo C:\Users\mrfin\Documents\lumen_v1_project -InlineConfig -Force

.NOTES
    Supports -WhatIf and -Confirm.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)]
    [string]$TargetRepo,

    [string]$OutputDir,

    [switch]$InlineConfig,

    [switch]$Force
)

$ErrorActionPreference = 'Stop'

# --- Build the project-specific "Resolved configuration" appendix from a parsed config ---
function Get-ConfigAppendix {
    param($Cfg, [string]$Today)

    $name = if ($Cfg.name) { $Cfg.name } else { 'this project' }
    $linkStyle = if ($Cfg.link_style) { $Cfg.link_style } else { 'markdown' }
    $linkExample = if ($linkStyle -eq 'obsidian') { '`[[relative/path]]` (no .md)' } else { '`[label](relative/path.md)`' }
    $deepScan = if ($null -ne $Cfg.deep_scan) { ([string]$Cfg.deep_scan).ToLower() } else { 'false' }

    $lines = @()
    $lines += ''
    $lines += '---'
    $lines += ''
    $lines += "## Appendix C — Resolved configuration for $name (auto-inlined)"
    $lines += ''
    $lines += "> Generated by ``deploy-protocol.ps1 -InlineConfig`` from ``.wiki-compiler.json`` on $Today."
    $lines += "> These are the concrete values for **$name**, so an agent can act without re-parsing the JSON."
    $lines += '> The live `.wiki-compiler.json` still wins if it has since changed — this is a deploy-time snapshot.'
    $lines += ''
    $lines += "- **mode:** ``$($Cfg.mode)``"
    $lines += "- **name:** ``$name``"
    $lines += "- **output:** ``$($Cfg.output)``"
    $lines += "- **link_style:** ``$linkStyle`` -> $linkExample"
    $lines += "- **deep_scan:** ``$deepScan``"

    if ($Cfg.sources) {
        foreach ($src in $Cfg.sources) {
            $ex = if ($src.exclude) { ($src.exclude -join ', ') } else { '(none)' }
            $lines += "- **source path:** ``$($src.path)`` — excludes: $ex"
        }
    }
    if ($Cfg.knowledge_files) {
        $lines += "- **knowledge_files:** $((($Cfg.knowledge_files) -join ', '))"
    }
    if ($Cfg.topic_hints) {
        $lines += "- **topic_hints:** $((($Cfg.topic_hints) -join ', '))"
    }

    if ($Cfg.article_sections) {
        $lines += '- **article_sections (use these exact sections, in order):**'
        $i = 1
        foreach ($s in $Cfg.article_sections) {
            $req = if ($s.required) { ' *(required)*' } else { '' }
            $lines += "  $i. **$($s.name)**$req — $($s.description)"
            $i++
        }
    }
    $lines += ''
    return ($lines -join "`r`n")
}

# --- Locate the master protocol (always next to this script) ---
$master = Join-Path $PSScriptRoot 'COMPILE_PROTOCOL.md'
if (-not (Test-Path -LiteralPath $master)) {
    throw "Master protocol not found at '$master'. Run this script from the llm-wiki-compiler repo."
}

# --- Validate target repo ---
if (-not (Test-Path -LiteralPath $TargetRepo -PathType Container)) {
    throw "Target repo '$TargetRepo' does not exist or is not a directory."
}
$TargetRepo = (Resolve-Path -LiteralPath $TargetRepo).Path

# --- Load config once (used for both output resolution and -InlineConfig) ---
$configPath = Join-Path $TargetRepo '.wiki-compiler.json'
$hasConfig  = Test-Path -LiteralPath $configPath
$cfg = $null
if ($hasConfig) {
    try {
        $cfg = Get-Content -LiteralPath $configPath -Raw | ConvertFrom-Json
    }
    catch {
        Write-Warning "Could not parse '$configPath' ($($_.Exception.Message)). Treating as no config."
        $cfg = $null
    }
}

# --- Resolve the output directory ---
if ($OutputDir) {
    $resolvedOut = $OutputDir
}
elseif ($cfg -and $cfg.output) {
    $resolvedOut = $cfg.output
}
else {
    $resolvedOut = 'wiki'
}

# Make the output dir absolute relative to the target repo if it is not already
$destDir = if ([System.IO.Path]::IsPathRooted($resolvedOut)) {
    $resolvedOut
} else {
    Join-Path $TargetRepo ($resolvedOut.TrimEnd('/', '\'))
}
$destFile = Join-Path $destDir 'COMPILE_PROTOCOL.md'

# --- Create the destination directory if needed ---
if (-not (Test-Path -LiteralPath $destDir)) {
    if ($PSCmdlet.ShouldProcess($destDir, 'Create directory')) {
        New-Item -ItemType Directory -Path $destDir -Force | Out-Null
    }
}

# --- Guard against silent overwrite (real runs must pass -Force) ---
if ((Test-Path -LiteralPath $destFile) -and -not $Force) {
    Write-Host "Skipped: '$destFile' already exists. Re-run with -Force to overwrite." -ForegroundColor Yellow
    return
}

# --- Copy (and optionally inline the project config) ---
if ($PSCmdlet.ShouldProcess($destFile, "Copy protocol from master")) {
    Copy-Item -LiteralPath $master -Destination $destFile -Force

    if ($InlineConfig) {
        if ($cfg) {
            $today = Get-Date -Format 'yyyy-MM-dd'
            $appendix = Get-ConfigAppendix -Cfg $cfg -Today $today
            Add-Content -LiteralPath $destFile -Value $appendix -Encoding UTF8
            Write-Host "Deployed + inlined config -> $destFile" -ForegroundColor Green
        }
        else {
            Write-Warning "-InlineConfig requested but no usable .wiki-compiler.json found. Deployed generic protocol only."
            Write-Host "Deployed COMPILE_PROTOCOL.md -> $destFile" -ForegroundColor Green
        }
    }
    else {
        Write-Host "Deployed COMPILE_PROTOCOL.md -> $destFile" -ForegroundColor Green
    }
}

# --- Post-deploy reminder about config ---
if (-not $hasConfig) {
    Write-Warning "No .wiki-compiler.json found in '$TargetRepo'."
    Write-Host  "  The protocol needs one to run. Create it (see Appendix A of the protocol) or run /wiki-init in that repo." -ForegroundColor Yellow
}
else {
    Write-Host "Found .wiki-compiler.json (output = '$resolvedOut'). Target is ready to compile." -ForegroundColor Cyan
}
