#!/usr/bin/env bash
#
# deploy-protocol.sh — POSIX counterpart of deploy-protocol.ps1
#
# Deploys the canonical, portable wiki COMPILE_PROTOCOL.md into a target repo.
# The master COMPILE_PROTOCOL.md lives next to this script. The destination
# directory is resolved in this order:
#   1. -o / --output-dir, if given
#   2. the "output" field of the target repo's .wiki-compiler.json (needs jq)
#   3. "wiki" (default)
#
# The protocol is project-agnostic: it reads all project-specific values from
# the target's .wiki-compiler.json at runtime, so nothing in the copied file
# needs editing. With -i / --inline-config, an auto-generated "Resolved
# configuration" appendix (built from .wiki-compiler.json) is appended to the
# deployed copy, specializing it for that project without manual drift.
#
# Usage:
#   ./deploy-protocol.sh [options] <target-repo>
#
# Options:
#   -o, --output-dir DIR   Override the output dir (relative to target, or absolute).
#   -i, --inline-config    Append a project-specific config appendix (requires jq).
#   -f, --force            Overwrite an existing COMPILE_PROTOCOL.md. Required to redeploy.
#   -n, --dry-run          Show what would happen; write nothing.
#   -h, --help             Show this help.
#
# Examples:
#   ./deploy-protocol.sh ~/Documents/some_project
#   ./deploy-protocol.sh -i -f ~/Documents/lumen_v1_project

set -euo pipefail

# --- Colors (only when stdout is a tty) ---
if [ -t 1 ]; then
  C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_CYAN=$'\033[36m'; C_RESET=$'\033[0m'
else
  C_GREEN=''; C_YELLOW=''; C_CYAN=''; C_RESET=''
fi
warn()  { printf '%sWarning:%s %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
info()  { printf '%s%s%s\n' "$C_CYAN" "$*" "$C_RESET"; }
ok()    { printf '%s%s%s\n' "$C_GREEN" "$*" "$C_RESET"; }
die()   { printf 'Error: %s\n' "$*" >&2; exit 1; }

usage() { sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

# --- Parse args ---
OUTPUT_DIR=""
INLINE_CONFIG=0
FORCE=0
DRY_RUN=0
TARGET_REPO=""

while [ $# -gt 0 ]; do
  case "$1" in
    -o|--output-dir)  OUTPUT_DIR="${2:?--output-dir needs a value}"; shift 2 ;;
    -i|--inline-config) INLINE_CONFIG=1; shift ;;
    -f|--force)       FORCE=1; shift ;;
    -n|--dry-run)     DRY_RUN=1; shift ;;
    -h|--help)        usage 0 ;;
    -*)               die "unknown option: $1" ;;
    *)                if [ -z "$TARGET_REPO" ]; then TARGET_REPO="$1"; else die "unexpected argument: $1"; fi; shift ;;
  esac
done

[ -n "$TARGET_REPO" ] || { warn "missing <target-repo>"; usage 1; }

# --- Locate the master protocol (always next to this script) ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
MASTER="$SCRIPT_DIR/COMPILE_PROTOCOL.md"
[ -f "$MASTER" ] || die "Master protocol not found at '$MASTER'. Run this script from the llm-wiki-compiler repo."

# --- Validate target repo ---
[ -d "$TARGET_REPO" ] || die "Target repo '$TARGET_REPO' does not exist or is not a directory."
TARGET_REPO="$(cd "$TARGET_REPO" && pwd)"

CONFIG_PATH="$TARGET_REPO/.wiki-compiler.json"
HAS_CONFIG=0; [ -f "$CONFIG_PATH" ] && HAS_CONFIG=1
HAS_JQ=0; command -v jq >/dev/null 2>&1 && HAS_JQ=1

# --- Resolve the output directory ---
if [ -n "$OUTPUT_DIR" ]; then
  RESOLVED_OUT="$OUTPUT_DIR"
elif [ "$HAS_CONFIG" -eq 1 ] && [ "$HAS_JQ" -eq 1 ]; then
  RESOLVED_OUT="$(jq -r '.output // "wiki"' "$CONFIG_PATH" 2>/dev/null || echo wiki)"
  [ -n "$RESOLVED_OUT" ] && [ "$RESOLVED_OUT" != "null" ] || RESOLVED_OUT="wiki"
else
  [ "$HAS_CONFIG" -eq 1 ] && [ "$HAS_JQ" -eq 0 ] && warn "jq not found — cannot read 'output' from config; defaulting to 'wiki'."
  RESOLVED_OUT="wiki"
fi

# Strip trailing slash; make absolute relative to the target repo if needed
RESOLVED_OUT="${RESOLVED_OUT%/}"
case "$RESOLVED_OUT" in
  /*) DEST_DIR="$RESOLVED_OUT" ;;
  *)  DEST_DIR="$TARGET_REPO/$RESOLVED_OUT" ;;
esac
DEST_FILE="$DEST_DIR/COMPILE_PROTOCOL.md"

# --- Build the project-specific appendix from .wiki-compiler.json ---
build_appendix() {
  local cfg="$1" today; today="$(date +%F)"
  local name link_style link_example
  name="$(jq -r '.name // "this project"' "$cfg")"
  link_style="$(jq -r '.link_style // "markdown"' "$cfg")"
  if [ "$link_style" = "obsidian" ]; then
    link_example='`[[relative/path]]` (no .md)'
  else
    link_example='`[label](relative/path.md)`'
  fi

  printf '\n---\n\n'
  printf '## Appendix C — Resolved configuration for %s (auto-inlined)\n\n' "$name"
  printf '> Generated by `deploy-protocol.sh --inline-config` from `.wiki-compiler.json` on %s.\n' "$today"
  printf '> These are the concrete values for **%s**, so an agent can act without re-parsing the JSON.\n' "$name"
  printf '> The live `.wiki-compiler.json` still wins if it has since changed — this is a deploy-time snapshot.\n\n'
  printf -- '- **mode:** `%s`\n' "$(jq -r '.mode // ""' "$cfg")"
  printf -- '- **name:** `%s`\n' "$name"
  printf -- '- **output:** `%s`\n' "$(jq -r '.output // ""' "$cfg")"
  printf -- '- **link_style:** `%s` -> %s\n' "$link_style" "$link_example"
  printf -- '- **deep_scan:** `%s`\n' "$(jq -r '.deep_scan // false' "$cfg")"
  jq -r '.sources[]? | "- **source path:** `\(.path)` — excludes: \((.exclude // []) | if length>0 then join(", ") else "(none)" end)"' "$cfg"
  if [ "$(jq -r '.knowledge_files | length' "$cfg" 2>/dev/null || echo 0)" -gt 0 ]; then
    printf -- '- **knowledge_files:** %s\n' "$(jq -r '.knowledge_files | join(", ")' "$cfg")"
  fi
  if [ "$(jq -r '.topic_hints | length' "$cfg" 2>/dev/null || echo 0)" -gt 0 ]; then
    printf -- '- **topic_hints:** %s\n' "$(jq -r '.topic_hints | join(", ")' "$cfg")"
  fi
  if [ "$(jq -r '.article_sections | length' "$cfg" 2>/dev/null || echo 0)" -gt 0 ]; then
    printf -- '- **article_sections (use these exact sections, in order):**\n'
    jq -r '.article_sections | to_entries[] | "  \(.key+1). **\(.value.name)**\(if .value.required then " *(required)*" else "" end) — \(.value.description)"' "$cfg"
  fi
  printf '\n'
}

# --- Create the destination directory if needed ---
if [ ! -d "$DEST_DIR" ]; then
  if [ "$DRY_RUN" -eq 1 ]; then
    info "What if: create directory '$DEST_DIR'"
  else
    mkdir -p "$DEST_DIR"
  fi
fi

# --- Guard against silent overwrite ---
if [ -f "$DEST_FILE" ] && [ "$FORCE" -eq 0 ]; then
  warn "Skipped: '$DEST_FILE' already exists. Re-run with --force to overwrite."
  exit 0
fi

# --- Copy (and optionally inline the project config) ---
if [ "$DRY_RUN" -eq 1 ]; then
  info "What if: copy protocol -> '$DEST_FILE'$([ "$INLINE_CONFIG" -eq 1 ] && echo ' (+ inlined config)')"
else
  cp "$MASTER" "$DEST_FILE"
  if [ "$INLINE_CONFIG" -eq 1 ]; then
    if [ "$HAS_CONFIG" -eq 1 ] && [ "$HAS_JQ" -eq 1 ]; then
      build_appendix "$CONFIG_PATH" >> "$DEST_FILE"
      ok "Deployed + inlined config -> $DEST_FILE"
    else
      [ "$HAS_JQ" -eq 0 ] && warn "--inline-config needs jq, which was not found. Deployed generic protocol only."
      [ "$HAS_JQ" -eq 1 ] && [ "$HAS_CONFIG" -eq 0 ] && warn "--inline-config requested but no .wiki-compiler.json found. Deployed generic protocol only."
      ok "Deployed COMPILE_PROTOCOL.md -> $DEST_FILE"
    fi
  else
    ok "Deployed COMPILE_PROTOCOL.md -> $DEST_FILE"
  fi
fi

# --- Post-deploy reminder about config ---
if [ "$HAS_CONFIG" -eq 0 ]; then
  warn "No .wiki-compiler.json found in '$TARGET_REPO'."
  printf '  The protocol needs one to run. Create it (see Appendix A of the protocol) or run /wiki-init in that repo.\n'
else
  info "Found .wiki-compiler.json (output = '$RESOLVED_OUT'). Target is ready to compile."
fi
